config/routes.rb
Rails.application.routes.draw do
  resources :user_calendars do
    collection do
      post 'import'
      post 'export'
    end
  end
  resources :events, except: [:new,  :edit, :update,  :index, :destroy] do
    collection do
      post 'embedded_index'
      post 'move_event'
      post 'embedded_new'
      post 'embedded_create'
    end
    member do
      post 'embedded_edit'
      patch 'embedded_update'
    end
  end
  resources :event_sets do
    collection do
      get 'weekly'
      post 'embedded_new'
      post 'embedded_create'
    end
    member do
      post 'embedded_edit'
      patch 'embedded_update'
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'event_sets#weekly'

end

app/models/event_set.rb
class EventSet < ActiveRecord::Base
  belongs_to :user_calendar
  has_many :events
  validates :title, :duration, :instances, presence:true

  # TODO need to support monthly and yearly events

  def start_at
    read_attribute(:start_at) || Time.now
  end


end

app/controllers/event_sets_controller.rb
class EventSetsController < ApplicationController
  respond_to :json


  def embedded_new
    @event_set = EventSet.new
  end

  def embedded_create
    tz = ActiveSupport::TimeZone.new(current_user.timezone)
    up_params = event_set_params
    up_params[:start_at] = tz.parse(up_params['start_at']).utc.to_s
    @event_set = EventSet.create(up_params)
  end

  def embedded_edit
     @event_set = EventSet.find(params[:id])
  end

  def embedded_update
    tz = ActiveSupport::TimeZone.new(current_user.timezone)
    up_params = event_set_params
    up_params[:start_at] = tz.parse(up_params['start_at']).utc.to_s
    @event_set = EventSet.find(params[:id])
    @event_set.update_attributes(up_params)
    render :embedded_create
  end

  def weekly
    @day = params[:day] ? Date.parse(params[:day]) : Date.today
    @first_day = @day.at_beginning_of_week
    @last_day = @first_day + 6.days
  end

  private

  def event_set_params
    params.require(:event_set).permit(:title, :description, :instances, :start_at, :duration, :period, :user_calendar_id)
  end
end

app/helpers/event_sets_helper.rb
module EventSetsHelper
end

app/views/event_sets/_event_set_edit.html.erb
<h2>Edit Event Set</h2>
<%= render :partial => 'event_set_form' %>
<div class="clearAll">
  <a href="/" , class="button buttonMid" , id="processEventButton" data-url="<%= embedded_update_event_set_path(@event_set) %>">Update</a>
  <a href="/" , class="button buttonMid" , id="cancelEventButton">cancel</a>
</div>

app/views/event_sets/_event_set_form.html.erb
<%= form_for @event_set, html: {id: 'event_data'} do |f| %>
    <% Time.use_zone(current_user.timezone) do %>
        <%= f.hidden_field 'event_set_id', value: @event_set.id %>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Title', 'Title', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.text_field :title, class: 'third-width' %></div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Description', 'Description', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.text_field :description, class: 'third-width' %></div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Instances', 'Instances', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.text_field :instances, class: 'third-width' %></div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Start', 'Start' %></div>
          <div class='twoThirds'><%= f.datetime_field :start_at,
                                                      value: @event_set.start_at.strftime('%Y/%m/%d %H:%M'),
                                                      class: 'timeSelection', :placeholder => 'mm/dd/yy' %></div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Duration(Minutes)', 'Duration(Minutes)', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.text_field :duration, class: 'third-width' %></div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Period(Days)', 'Period(Days)', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.text_field :period, class: 'third-width' %></div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Calendar', 'Calendar', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.select :user_calendar_id, options_from_collection_for_select(current_user.user_calendars, 'id', 'name', @event_set.user_calendar_id) %></div>
        </div>
    <% end %>
<% end %>

app/views/event_sets/_event_set_new.html.erb
<h2 class="'leftSide twoThirds">New Event Set</h2>
<a href="/" class="button buttonMid rightSide"
   id="editEventSet"
   data-url="<%= embedded_new_events_path %>">New Event</a>

<%= render :partial => 'event_set_form' %>
<div class="clearAll">
  <a href="/" , class="button buttonMid" , id="processEventButton" data-url="<%= embedded_create_event_sets_path %>">create</a>
  <a href="/" , class="button buttonMid" , id="cancelEventButton">cancel</a>
</div>

app/views/event_sets/embedded_create.js.erb
PHR.Events.weekdayInit();

app/views/event_sets/embedded_edit.js.erb
$('#eventDialog').html('<%= escape_javascript( render :partial => 'event_set_edit',
                                                                  :formats => [:html]) %>');
$('#eventDialog').dialog('open')
PHR.Events.dialogInit();

app/views/event_sets/embedded_new.js.erb
$('#eventDialog').html('<%= escape_javascript( render :partial => 'event_set_new',
                                                      :formats => [:html]) %>');
$('#eventDialog').dialog('open')
PHR.Events.dialogInit();

app/views/event_sets/weekly.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'week' %>
<% end %>

<div class="filters">
  <p class="filtertext">Week of <br /><%= @day.to_s %></p>
  <div class="clearAll" style="margin-top: 10px">
    <a href="<%= weekly_event_sets_path(day: (@day - 7.days)) %>"  class="button buttonMid">Prev</a>
    <a href="<%= weekly_event_sets_path(day: (@day + 7.days)) %>"  class="button buttonMid" >Next</a>
  </div>
  <h3>Calendars</h3>
  <% current_user.user_calendars.each do |calendar| %>
      <%= check_box_tag "calendar_#{calendar.id}", "calendar_#{calendar.id}", true, {class: 'calendarSelection'} %>
      <span class='calendarPalette'><%= calendar.name %></span><br/>
  <% end %>
  <div class="clearAll" style="margin-top: 10px">
    <a href="<%= user_calendars_path %>"  class="button buttonMid"  id="adjustCalendarsButton" >Edit Calendars</a>
  </div>
  <div class="clearAll">
    <a href="/"  class="button buttonMid"  id="addEventButton" data-url="<%= embedded_new_events_path %>" >New Event</a>
  </div>
</div>
<div>
  <div class="hourCaption"   style="border-bottom: solid 1px;">Hour</div>
  <% (@first_day..@last_day).each do |day| %>
  <div class="weekday"  style="border-bottom: solid 1px;"><%= day.strftime('%A') %></div>
  <% end %>
</div>
<div class="weekBox">
  <div class="hourColumn">
    <% (0..23).each do |hour| %>
        <div class="hourCaption hourBox"><span class='hourLabel'><%= '%02d' % hour %>:00</span></div>
    <% end %>
  </div>
  <% (@first_day..@last_day).each do |day| %>
      <div class="weekday" id="day_<%= day %>" data-day="<%= day %>"
           data-move-url="<%= move_event_events_path %>"
           data-populate-url="<%= embedded_index_events_path(date: day) %>">
        <% (0..23).each do |hour| %>
            <div class="hourBox"></div>
        <% end %>
      </div>
  <% end %>
</div>
<div id="eventDialog"></div>