config/routes.rb
Rails.application.routes.draw do
  resources :user_calendars do
    collection do
      post 'import'
      post 'export'
    end
  end
  resources :events, except: [:new,  :edit, :update,  :index, :destroy] do
    collection do
      post 'embedded_index'
      post 'move_event'
      post 'embedded_new'
      post 'embedded_create'
    end
    member do
      post 'embedded_edit'
      patch 'embedded_update'
    end
  end
  resources :event_sets do
    collection do
      get 'weekly'
      post 'embedded_new'
      post 'embedded_create'
    end
    member do
      post 'embedded_edit'
      patch 'embedded_update'
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'event_sets#weekly'

end

app/models/user_calendar.rb
class UserCalendar < ActiveRecord::Base
  has_many :events
  has_many :event_sets

  VISIBILITY_LEVELS=%w(PRIVATE LIMITED PUBLIC)
  validates :visibility, inclusion: {in: VISIBILITY_LEVELS}
  validates :name, presence: true

  def import_events(ics_file)
    cal_file = File.open(ics_file)
    cals = Icalendar.parse(cal_file)
    cal = cals.first
    cal.events.each do |event|
      if event.rrule.count > 0
        rule = event.rrule.first
        #Rails.logger.info "Rule #{rule.to_json}"
        if rule.interval.nil?
          interval = 1
          interval_units = 'DAYS'
        else
          case rule.frequency # TODO fix yearly and monthy after event set supports
            when "MONTHLY"
              interval_units = 'MONTHS'
              interval = rule.interval.to_i
            when "WEEKLY"
              interval_units = 'DAYS'
              interval = 7 * rule.interval.to_i
            when "YEARLY"
              interval_units = 'YEARS'
              interval = rule.interval.to_i
            else
              interval_units = 'DAYS'
              interval = rule.interval.to_i
          end
        end
        #Rails.logger.info "Event name #{event.summary}, start #{event.dtstart} end #{event.dtend}"
        if event.dtend.nil?
          duration = 15
        else
          duration = (event.dtend.to_time - event.dtstart.to_time).to_i.abs/60
        end
        if rule.count.nil? && rule.until.nil?
          instances = 0
          has_end = false
        else
          if rule.until.nil?
            instances = rule.count
            has_end = true
          else
            instances = ((rule.until.to_time - event.dtstart.to_time)/(interval * 86400)).to_i
            has_end = true
          end
        end
        self.event_sets.create(title: event.summary,
                               description: event.description,
                               start_at: event.dtstart,
                               duration: duration,
                               period: interval,
                               interval_units: interval_units,
                               instances: instances,
                               has_end: has_end)
      else
        self.events.create(title: event.summary,
                           description: event.description,
                           start_at: event.dtstart,
                           end_at: event.dtend)
      end
    end
  end

end

app/controllers/user_calendars_controller.rb
class UserCalendarsController < ApplicationController
  def create
    new_cal = UserCalendar.create(calendar_params)
    CalendarAccess.create(user_id: current_user.id,
                          user_calendar_id: new_cal.id,
                          access_level: 'FULL')
    @calendars = current_user.user_calendars
    render :index
  end

  def update
    @calendar = UserCalendar.find(params['id'])
    @calendar.update_attributes(calendar_params)
    @calendars = current_user.user_calendars
    render :index
  end

  def destroy
    target_cal = UserCalendar.find(params['id'])
    cal_access = current_user.calendar_accesses.where(user_calendar_id: target_cal.id).first
    if cal_access.access_level == 'FULL' # You can only delete you own calendars
      target_cal.destroy
    else # otherwise we just remove your access
      cal_access.destroy
    end
    @calendars = current_user.user_calendars
    render :index
  end

  def index
    @calendars = current_user.user_calendars
  end

  def new
    @calendar = UserCalendar.new
    render :edit
  end

  def edit
    @calendar = UserCalendar.find(params['id'])
  end

  def import
    @calendar = UserCalendar.find(params['import_calendar_id'])
    in_cal = params[:import_file]
    @calendar.import_events(in_cal.tempfile)
    redirect_to '/'
  end

  def export

  end

  private

  def calendar_params
    params.require(:user_calendar).permit(:name, :description, :color, :visibility)
  end
end

app/helpers/user_calendars_helper.rb
module UserCalendarsHelper
end

app/views/user_calendars/_calendar_entry.html.erb
<div class="clearAll calendarLine">
  <div class='calendarEntryKey' style="background-color:<%= calendar_entry.color %>;"></div>
  <%= link_to calendar_entry.name, edit_user_calendar_path(calendar_entry) %>
  <%= calendar_entry.visibility %>
  <%= calendar_entry.event_sets.count %> event sets &nbsp;
  <%= calendar_entry.events.count %> events &nbsp;
  <%= link_to 'import', '/', {class: 'calendarImport button buttonMid', data: {calendarId: calendar_entry.id}} %>
  <%= link_to 'export', '/', {class: 'calendarExport button buttonMid', data: {calendarId: calendar_entry.id}} %>
  <%= link_to 'delete', user_calendar_path(calendar_entry), :method =>:delete, confirm: 'Are you sure?', class: 'button buttonMid' %>
</div>

app/views/user_calendars/edit.html.erb
<%= form_for @calendar do |f| %>
    <% if f.object.errors.count > 0 %>
        <fieldset>
          <legend>Errors Encountered</legend>
          <% f.object.errors.full_messages.each do |message| %>
              <%= message %>
              <br/>
          <% end %>
        </fieldset>
        <br />
    <% end %>

    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Name', 'Name', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.text_field :name , class: 'third-width' %></div>
    </div>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Visibility', 'Visibility', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.select :visibility, options_for_select(UserCalendar::VISIBILITY_LEVELS, @calendar.visibility) %></div>
    </div>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Description', 'Description', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.text_area :description, class: 'third-width' %></div>
    </div>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Color', 'Color', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.color_field :color , class: 'third-width' %></div>
    </div>
    <div class="formLine clearAll">
    <%= f.submit @calendar.new_record? ? 'Create' : 'Save' %>
    </div>
<% end %>

app/views/user_calendars/index.html.erb
<% content_for :head do %>
    <%= javascript_include_tag 'calendar' %>
<% end %>
<h3>Visible Calendars</h3>
<div id="calendarImportDialog" class="minimized">
  <%= form_tag import_user_calendars_path, multipart: true do %>
      <% label_tag '.ics File', '.ics File' %>
      <%= hidden_field_tag 'import_calendar_id', 0 %>
      <%= file_field_tag 'import_file' %>
      <%= submit_tag 'Import' %>
  <% end %>
</div>
<div id="calendarExportDialog" class="minimized">
  <%= form_tag export_user_calendars_path do %>
      <%= hidden_field_tag 'export_calendar_id', 0 %>
      <%= file_field_tag 'export_file' %>
      <%= submit_tag 'Export' %>
  <% end %>
</div>
<div>
  <%= render partial: 'calendar_entry', collection: @calendars %>
</div>

<div class="clearAll" style="margin-top: 10px">
  <a href="<%= new_user_calendar_path %>" class="button buttonMid">New Calendar</a>
  <a href="<%= weekly_event_sets_path %>" class="button buttonMid">Cancel</a>
</div>