config/routes.rb
Rails.application.routes.draw do
  resources :user_calendars do
    collection do
      post 'import'
      post 'export'
    end
  end
  resources :events, except: [:new,  :edit, :update,  :index, :destroy] do
    collection do
      post 'embedded_index'
      post 'move_event'
      post 'embedded_new'
      post 'embedded_create'
    end
    member do
      post 'embedded_edit'
      patch 'embedded_update'
    end
  end
  resources :event_sets do
    collection do
      get 'weekly'
      post 'embedded_new'
      post 'embedded_create'
    end
    member do
      post 'embedded_edit'
      patch 'embedded_update'
    end
  end
  devise_for :users, :controllers => { :registrations => "registrations" }

  root 'event_sets#weekly'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user_calendar
  has_one :event_set
  validates :title, presence:true

  def start_at
    read_attribute(:start_at) || Time.now
  end

  def end_at
    read_attribute(:end_at) || Time.now + 30.minutes
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :json

  def embedded_index
    @day = Date.parse(params[:date])
    @events = current_user.appointments(@day)
  end

  def embedded_edit
    @event = Event.find(params[:id])
  end

  def embedded_new
    @event = Event.new
    @event.user_calendar = current_user.default_calendar
  end

  def embedded_update
    tz = ActiveSupport::TimeZone.new(current_user.timezone)
    up_params = event_params
    up_params[:start_at] = tz.parse(up_params['start_at']).utc.to_s
    up_params[:end_at] = tz.parse(up_params['end_at']).utc.to_s
    @event = Event.find(params['event_id'])
    @old_day = @event.start_at.to_date
    @event.update_attributes(up_params)
    @day = @event.start_at.to_date
    @events = current_user.appointments(@day)
    @old_day_events = current_user.appointments(@old_day)
    render :move_event
  end

  def embedded_create
    tz = ActiveSupport::TimeZone.new(current_user.timezone)
    up_params = event_params
    up_params[:start_at] = tz.parse(up_params['start_at']).utc.to_s
    up_params[:end_at] = tz.parse(up_params['end_at']).utc.to_s
    @event = Event.create(up_params)
    @day = @event.start_at.to_date
    @events = current_user.appointments(@day)
    render :embedded_index
  end

  def move_event
    @event = Event.find(params[:event_id])
    duration =  @event.end_at.to_time - @event.start_at.to_time
    @old_day = @event.start_at.to_date
    @day = Date.parse(params[:target_date])
    hours = params[:target_hour].to_f
    start_at = (@day.to_time + hours * 3600)
    adjust_sec = start_at.sec
    adjust_min  = start_at.min % current_user.snap_to_minutes
    Rails.logger.info "Adjusting #{start_at.to_s} by #{adjust_min} minutes and #{adjust_sec} seconds"
    @event.start_at =  start_at - adjust_min.minutes - adjust_sec.seconds
    @event.end_at = start_at + duration.seconds
    @event.save
    @old_day_events = current_user.appointments(@old_day)
    @events = current_user.appointments(@day)
  end

  private

  def event_params
    params.require(:event).permit(:title, :description, :notes, :start_at, :end_at, :user_calendar_id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<% duration = event.end_at - event.start_at %>
<% top = event.start_at.in_time_zone(current_user.timezone).seconds_since_midnight/86400 * ENV['DAY_HEIGHT'].to_i %>
<div  class='event-entry'
      style='top:<%= top %>px;height: <%= ENV['DAY_HEIGHT'].to_i/24 * duration/3600%>px' data-id="<%= event.id %>"
      title="<%= "#{event.title}, From #{event.start_at.in_time_zone(current_user.timezone).strftime('%H:%M')} to #{event.end_at.in_time_zone(current_user.timezone).strftime('%H:%M')} " %>">
  <p class="button buttonSmall editButton"><a class='eventEditButton' data-edit-url='<%= embedded_edit_event_path(event) %>' href="/">e</a> </p>
  <p class='event-title'>  <%= event.title %> </p>
</div>

app/views/events/_event_edit.html.erb
<h2>Edit Event</h2>
<% if @event.event_set_id %>
    <a href="/"
       class="button buttonMid rightSide"
       id="editEventSet"
       data-url="<%= embedded_edit_event_set_path(@event.event_set_id) %>">Edit Event Set</a>
<% end %>
<%= render :partial => 'event_form' %>
<div class="clearAll">
  <a href="/" , class="button buttonMid" , id="processEventButton" data-url="<%= embedded_update_event_path(@event) %>">Update</a>
  <a href="/" , class="button buttonMid" , id="cancelEventButton">cancel</a>
</div>

app/views/events/_event_form.html.erb
<%= form_for @event, html: {id: 'event_data'} do |f| %>

    <%= hidden_field_tag 'event_id', @event.id %>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Title', 'Title', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.text_field :title, class: 'third-width' %></div>
    </div>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Description', 'Description', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.text_field :description, class: 'third-width' %></div>
    </div>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Notes', 'Notes', class: 'third-width' %></div>
      <div class='twoThirds'><%= f.text_field :notes, class: 'third-width' %></div>
    </div>
    <% Time.use_zone(current_user.timezone) do %>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'Start', 'Start' %></div>
          <div class='twoThirds'><%= f.datetime_field :start_at,
                                                      value: @event.start_at.strftime('%Y/%m/%d %H:%M'),
                                                      class: 'timeSelection third-width' %>
          </div>
        </div>
        <div class="formLine clearAll">
          <div class='thirdWidth'><%= label 'End', 'End', class: 'third-width' %></div>
          <div class='twoThirds'><%= f.datetime_field :end_at,
                                                      value: @event.end_at.strftime('%Y/%m/%d %H:%M'),
                                                      class: 'timeSelection third-width' %>
          </div>
        </div>
    <% end %>
    <div class="formLine clearAll">
      <div class='thirdWidth'><%= label 'Calendar', 'Calendar', class: 'third-width' %></div>
      <div class='twoThirds'>
        <%= f.select :user_calendar_id,
                     options_from_collection_for_select(current_user.user_calendars,
                                                        'id',
                                                        'name',
                                                        @event.user_calendar_id) %>
      </div>
    </div>


<% end %>

app/views/events/_event_list.html.erb
<fieldset class="dayBox">
  <legend><%= @day.to_s %></legend>
  <div class="dayPage">
    <% (0..23).each do |hour| %>
        <div class="hourBox"></div>
    <% end %>
    <div class="event-list">
      <%= render partial: 'event', collection: events %>
    </div>
  </div>
  <div className='event_dialog' id='event_dialog'>
  </div>
</fieldset>

app/views/events/_event_new.html.erb
<h2 class="'leftSide twoThirds">New Event</h2>
<a href="/" class="button buttonMid rightSide"
   id="editEventSet"
   data-url="<%= embedded_new_event_sets_path %>">New Event Set</a>

<%= render :partial => 'event_form' %>
<div class="clearAll">
  <a href="/" , class="button buttonMid" , id="processEventButton" data-url="<%= embedded_create_events_path %>">create</a>
  <a href="/" , class="button buttonMid" , id="cancelEventButton">cancel</a>
</div>

app/views/events/embedded_edit.js.erb
<% Rails.logger.info render :partial => 'event_form',
                            :formats => [:html] %>
<% Rails.logger.info render :partial => 'event_edit',
                            :formats => [:html] %>
$('#eventDialog').html('<%= escape_javascript( render :partial => 'event_edit',
                                                      :formats => [:html]) %>');
$('#eventDialog').dialog('open')
PHR.Events.dialogInit();

app/views/events/embedded_index.js.erb
$('#day_<%= @day %>').html('<%= escape_javascript( render :partial => 'event_list',
                                                                      locals: {events: @events} ,
                                                                     :formats => [:html]) %>');

app/views/events/embedded_new.js.erb
$('#eventDialog').html('<%= escape_javascript( render :partial => 'event_new',
                                                      :formats => [:html]) %>');
$('#eventDialog').dialog('open')
PHR.Events.dialogInit();

app/views/events/move_event.js.erb
$('#day_<%= @old_day %>').html('<%= escape_javascript( render :partial => 'event_list',
                                                                           locals: {events: @old_day_events} ,
                                                                           :formats => [:html]) %>');
$('#day_<%= @day %>').html('<%= escape_javascript( render :partial => 'event_list',
                                                                      locals: {events: @events} ,
                                                                     :formats => [:html]) %>');